version: '3'

services:
  payload:
    image: node:18-alpine
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command:  sh -c "yarn install && yarn dev"
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_USER=$DB_USER
      - POSTGRES_DB=$DB_NAME
    env_file:
      - .env

volumes:
  data:
  node_modules:
